### ISSUE TITLE
Jamf doesn't think com.microsoft.autoupdate2 is valid

### ISSUE THREAD

**Issue by staze** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#30] opened 2024-10-21 20:53 UTC
Jamf Pro 11.10.1 doesn't allow importing com.microsoft.autoupdate2.json. Says it's invalid.

https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/blob/main/manifests/ManagedPreferencesApplications/com.microsoft.autoupdate2.json

"Invalid JSON schema. Ensure the properties and values are correct."

Json validators all seem fine. Other schema's import fine. Not sure what the issue is.

**Comment by homebysix** [comment] 2024-10-21 22:25
Duplicate of: https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/issues/8

**Closed by homebysix** 2024-10-21 22:25 UTC
